apiVersion: v1
kind: Service
metadata:
  name: {{ required "values.name is required" .Values.name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | quote }}
    app.kubernetes.io/part-of: online-shop
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.name | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

