apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: online-shop
spec:
  project: default
  source:
    repoURL: https://github.com/DimitryZH/sre-platform
    targetRevision: main
    path: charts/platform
    helm:
      releaseName: online-shop
  destination:
    server: https://kubernetes.default.svc
    namespace: online-shop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
