apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: online-shop
spec:
  project: default
  source:
    repoURL: https://github.com/DimitryZH/sre-platform
    targetRevision: main
    path: charts/platform
    helm:
      releaseName: online-shop
      values: |
        image:
          repository: docker.io/dmitryzhuravlev/online-shop-frontend
          tag: "v0.10.4"
        service:
          port: 8080
        rollouts:
          enabled: true
          analysis:
            prometheusAddress: http://prometheus-operated.monitoring:9090
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
