{{- if .Values.break.enabled -}}
{{- $host := (printf "frontend.%s" (.Values.global.domain | default "example.com")) -}}
{{- $useHost := .Values.frontend.ingress.useHost -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-break
  labels:
    app.kubernetes.io/part-of: online-shop
  annotations:
    # Rewrite /break to an httpbin endpoint that returns a 500.
    nginx.ingress.kubernetes.io/rewrite-target: /status/500
spec:
  ingressClassName: nginx
  rules:
    - {{- if $useHost }}
      host: {{ $host | quote }}
      {{- end }}
      http:
        paths:
          - path: /break
            pathType: Exact
            backend:
              service:
                name: break-500
                port:
                  name: http
{{- end }}

