apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-platform-stage
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: online-shop
spec:
  project: default
  source:
    repoURL: https://github.com/DimitryZH/sre-platform
    targetRevision: main
    path: environments/stage/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

