apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DimitryZH/sre-platform'
    path: 'charts/platform'
    targetRevision: main
    helm:
      releaseName: online-shop
      values: |
        image:
          repository: docker.io/dmitryzhuravlev/online-shop-frontend
          tag: "v0.10.4"
        service:
          port: 8080
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true