apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-metrics-stage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/DimitryZH/sre-platform
    targetRevision: main
    path: environments/stage/argocd/ingress-nginx-metrics
