apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-stage
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: online-shop
    env: stage
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: online-shop-stage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/DimitryZH/sre-platform
      targetRevision: main
      path: charts/platform
      helm:
        releaseName: online-shop-stage
        valueFiles:
          - $values/environments/stage/values/platform.yaml
    - repoURL: https://github.com/DimitryZH/sre-platform
      targetRevision: main
      ref: values